#!/usr/bin/env mksh
#
#
# === {{CMD}} lib|app
# === Run this command AFTER creating the repo.

local +x NAME="$(basename "$PWD")"
local +x REPO_TYPE

if [[ -n "$@" ]]; then
  local +x REPO_TYPE="$1"; shift
else
  echo "=== lib or app? (app): " >&2
  read -r ANS
  case "$ANS" in
    lib) REPO_TYPE=lib ;;
    *) REPO_TYPE=app ;;
  esac
fi

{
  if [[ $REPO_TYPE == "lib" ]]; then
    echo "/shard.lock"
  fi

  echo "/.shards/"
} >> .gitignore

local +x NEW_GITIGNORE="$(cat .gitignore | awk '!seen[$0]++' )"
echo "$NEW_GITIGNORE" > .gitignore

mkdir -p src specs

if [[ -e "shard.yml" ]]; then
  crystal deps
else
  echo "name: $NAME"    >> shard.yml
  echo "version: 0.1.0" >> shard.yml
  echo "dependencies:"  >> shard.yml
  echo "  exit_on_error:" >> shard.yml
  echo "    github: da99/exit_on_error" >> shard.yml
  echo "  shell_out:" >> shard.yml
  echo "    github: da99/shell_out" >> shard.yml
fi

