#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"

local +x old_ver="$("$THIS_BINARY" version)"
"$THIS_BINARY" bump $@
local +x new_ver="$("$THIS_BINARY" version)"

echo "OLD: ${old_ver}"
echo "NEW: ${new_ver}"
git add shard.yml
git commit -m "Bump: v${new_ver}"
git tag "v${new_ver}"
git push
git push origin "v${new_ver}"

