#!/usr/bin/env zsh
#
# === {{CMD}} [--url] [PATTERN]
#
set -u -e -o pipefail

local +x PRINT_URL=""
if [[ "${1:-}" == "--url" ]]; then
  PRINT_URL="yes"; shift
fi

local +x PATTERN=""
local +x URL="https://github.com/crystal-lang/crystal/releases"

if [[ -z "$@" ]]; then
  case "$(uname -a)" in
    *" x86_64 GNU/Linux") PATTERN+="linux-x86_64" ;;
    *) echo "!!! Unknown architecture: $(uname -a)" >&2; exit 5 ;;
  esac
else
  PATTERN="${PATTERN}${1}"; shift
fi


local +x URL="$(lynx --dump "$URL" | grep -P "releases/download.+$PATTERN.+" | tr -s ' ' | cut -d' ' -f3 | sort --version-sort | tail -n1)"

if [[ -z "$URL" ]]; then
  echo "!!! Could not find latest url for: $PATTERN" >&2
  exit 5
fi

if [[ "$PRINT_URL" == "yes" ]]; then
  echo $URL
else
  echo "$(basename "$URL" .tar.gz)"
fi
