#!/usr/bin/env zsh
#
# === {{CMD}}
# === {{CMD}} XX.XX.XX  i686|x86_64
#
set -u -e -o pipefail

local +x PATTERN="download.+"
local +x URL="https://github.com/crystal-lang/crystal/releases"

if [[ -n "$@" ]]; then
  PATTERN="${PATTERN}${1}.+"; shift
fi

local +x ARCH="$@"
if [[ -n "$ARCH" ]]; then
  PATTERN="${PATTERN}${1}.+"; shift
else
  case "$(uname -a)" in
    *" x86_64 GNU/Linux") PATTERN+="linux-x86_64.+" ;;
    *" i686 GNU/Linux") PATTERN+="linux-i686.+" ;;
    *) echo "!!! Unknown architecture: $(uname -a)" >&2; exit 5 ;;
  esac
fi

lynx --dump "$URL" | grep -P "releases/$PATTERN" | tr -s ' ' | cut -d' ' -f3 | sort --version-sort | tail -n1
