#!/usr/bin/env mksh
#

# === {{CMD}}

PATH="$PATH:$THIS_DIR/../sh_color/bin"
PATH="$PATH:$THIS_DIR/../process/bin"
PATH="$PATH:$THIS_DIR/../my_network/bin"
PATH="$PATH:$THIS_DIR/bin"
PATH="$PATH:$THIS_DIR/tmp/latest-crystal/bin"

cd "$THIS_DIR"
mkdir -p "tmp/in" "tmp/out"

if [[ ! -z "$@" ]] ; then
  echo "=== Compiling... $(date "+%H:%M:%S") ..." >&2

  local +x FILE="tmp/in/scratch.cr"
  if [[ ! -f "$FILE" ]]; then
    sh_color RED "=== File does not exist: {{$FILE}}"
  fi

  mkdir -p tmp/bin
  cd tmp
  my_crystal __ build "./in/scratch.cr" -o ./out/scratch
  if grep "server.listen" "./in/scratch.cr" ; then
    pkill -f "./out/scratch" || :
    sh_color ORANGE "=== {{Running}}..."
    ( ./out/scratch || : ) &
    sleep 1
    my_network inspect http://localhost:3000/ && echo
    my_network inspect http://localhost:3000/hello/world && echo
    my_network inspect http://localhost:3000/hello/the/entire/world && echo
  else
    sh_color ORANGE "=== {{Running}}..."
    ./out/scratch && sh_color GREEN "=== {{DONE}} ===" || sh_color RED "=== {{DONE}} ==="
  fi

else
  local +x CMD="my_crystal scratch run"
  $CMD || :
  process watch "-r bin -r sh -r tmp/in" "$CMD"

fi


