#!/usr/bin/env mksh
#

# === {{CMD}}

PATH="$PATH:$THIS_DIR/../sh_color/bin"
PATH="$PATH:$THIS_DIR/../mksh_setup/bin"
PATH="$PATH:$THIS_DIR/bin"
PATH="$PATH:$THIS_DIR/tmp/latest-crystal/bin"

cd "$THIS_DIR"

if [[ ! -z "$@" ]] ; then
  echo "=== Compiling... $(date "+%H:%M:%S") ..." >&2

  local +x FILE="tmp/scratch.cr"
  if [[ ! -f "$FILE" ]]; then
    sh_color "=== File does not exist: {{$FILE}}"
  fi

  mkdir -p tmp/bin
  cd tmp
  my_crystal __ build ./scratch.cr -o ./bin/my.scratch
  echo "=== Running..."
  ./bin/my.scratch && sh_color GREEN "=== {{DONE}} ===" || sh_color RED "=== {{DONE}} ==="

else
  local +x CMD="my_crystal watch run"
  $CMD || :
  mksh_setup watch "bin tmp" "$CMD"

fi


