#!/usr/bin/env mksh
#

# === {{CMD}}

PATH="$PATH:$THIS_DIR/../sh_color/bin"
PATH="$PATH:$THIS_DIR/../mksh_setup/bin"
PATH="$PATH:$THIS_DIR/bin"
PATH="$PATH:$THIS_DIR/progs/latest-crystal/bin"
PATH="$PATH:$THIS_DIR/progs/latest-shards/bin"

cd "$THIS_DIR"

if [[ ! -z "$@" ]] ; then
  echo "=== Compiling... $(date "+%H:%M:%S") ..." >&2

  local +x FILE="tmp/scratch.cr"
  if [[ ! -f "$FILE" ]]; then
    sh_color "=== File does not exist: {{$FILE}}"
  fi

  crystal build tmp/scratch.cr -o /tmp/my.crystal.scratch
  echo "=== Running..."
  /tmp/my.crystal.scratch && sh_color GREEN "=== {{DONE}} ===" || sh_color RED "=== {{DONE}} ==="
else
  local +x CMD="my_crystal watch run"
  $CMD || :
  mksh_setup watch "-r bin -r tmp" "$CMD"
fi

